# Generated by Django 2.2.22 on 2021-05-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplemesh', '0002_thought_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='title_text',
            new_name='text',
        ),
    ]
